AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/bundle/**/*
  NewCops: enable
  TargetRubyVersion: 2.4

require:
  - rubocop-performance
  - rubocop-rspec

Layout/ArgumentAlignment:
  EnforcedStyle: "with_fixed_indentation"

Layout/BlockAlignment:
  EnforcedStyleAlignWith: 'start_of_block'

Layout/FirstHashElementIndentation:
  EnforcedStyle: 'consistent'

Layout/LineLength:
  AutoCorrect: true
  IgnoredPatterns: ['\A\s*#']
  Max: 80

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: 'indented'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: 'required'

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: 'brackets'
